
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int NUMERO_UNO = 2;
  public static final int EOF = 0;
  public static final int NUMERO_CERO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO_UNO",
  "NUMERO_CERO"
  };
}

